name: Build App
on:
  push:
    branches:
      - develop
jobs:
  android:
    runs-on: ubuntu-latest
    steps: 
      - name: Install yarn dependencies
        uses: actions/checkout@v2.1.0
        run: |
          yarn install
    - name: Run tests
        uses: actions/checkout@v2.1.0
        run: |
          yarn test
     