name: Build App
on:
  push:
    branches:
      - develop
jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '12'
        run: yarn install
      
     