name: Build Android
on:
  push:
    branches:
      - develop
jobs:
  install:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn install
   teste:
    needs: install
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn test
     