name: Build App
on:
  push:
    branches:
      - develop
jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn install
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Make envFile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_ONE_SIGNAL_KEY: ${{ secrets.ONE_SIGNAL_KEY }}
          envkey_ONE_SIGNAL_PROJECT_NUMBER: ${{ secrets.ONE_SIGNAL_PROJECT_NUMBER }}
          envkey_CODE_PUSH_DEPLOYMENT_KEY: ${{ secrets.CODE_PUSH_DEPLOYMENT_KEY }}
          envkey_API_URL: ${{ secrets.API_URL }}
          file_name: .env
      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
  ios:
    name: Build iOS
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build app
        run: |       
          cd ios && xcodebuild -workspace isusapp.xcworkspace -scheme isusapp archive -archivePath isusapp.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./githubPoc.xcarchive -exportPath . -exportOptionsPlist isusapp/Info.plist
          mv isusapp.ipa ../isusapp.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: isusapp.ipa
          path: ios/build/
