name: Build App
on:
  push:
    branches:
      - develop
jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease 
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      
     